# Generated by Django 3.2.3 on 2021-11-12 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20211112_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.month'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.date'),
        ),
    ]
