# Generated by Django 3.2.7 on 2021-12-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20211112_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub',
        ),
    ]
