# Generated by Django 3.2.7 on 2021-12-15 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_remove_task_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.name'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.date'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fromm',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.month'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='to',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
